import { Typography } from "@/components/typography";

export default function CookiePolicy() {
  return (
    <div className="container mx-auto px-4 my-10">
      <div className="flex flex-col gap-4">
        <Typography variant="h1" text="Cookie Policy" />
        <Typography variant="p" text="Updated at 2025-02-14" />

        <Typography variant="h1" text="Definitions and key terms" />
        <Typography
          variant="p"
          text="To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:"
        />
        <ul>
          <li>
            Cookie: small amount of data generated by a website and saved by your web browser. It is
            used to identify your browser, provide analytics, remember information about you such as
            your language preference or login information.
          </li>
          <li>
            Company: when this policy mentions &ldquo;Company,&rdquo; &ldquo;we,&rdquo;
            &ldquo;us,&rdquo; or &ldquo;our,&rdquo; it refers to Mikael Boutin, that is responsible
            for your information under this Cookie Policy.
          </li>
          <li>
            Device: any internet connected device such as a phone, tablet, computer or any other
            device that can be used to visit PokeSwap.io and use the services.
          </li>
          <li>
            Personal Data: any information that directly, indirectly, or in connection with other
            information — including a personal identification number — allows for the identification
            or identifiability of a natural person.
          </li>
          <li>
            Service: refers to the service provided by PokeSwap.io as described in the relative
            terms (if available) and on this platform.{" "}
          </li>
          <li>
            Third-party service: refers to advertisers, contest sponsors, promotional and marketing
            partners, and others who provide our content or whose products or services we think may
            interest you.
          </li>
          <li>Website: site, which can be accessed via this URL: https://pokeswap.io</li>
        </ul>
        <p>
          This Cookie Policy was created with{" "}
          <a href="https://termify.io" target="_blank">
            Termify
          </a>
          .
        </p>

        <Typography variant="h1" text="Introduction" />
        <Typography
          variant="p"
          text={`This Cookie Policy explains how PokeSwap.io and its affiliates (collectively &ldquo;PokeSwap.io&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, and &ldquo;ours&rdquo;), use cookies and similar technologies to recognize you when you visit our website, including without limitation https://pokeswap.io and any related URLs, mobile or localized versions and related domains / sub-domains (&ldquo;Websites&rdquo;). It explains what these technologies are and why we use them, as well as the choices for how to control them.`}
        />

        <Typography variant="h1" text="What is a cookie?" />
        <Typography
          variant="p"
          text={`A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They&rsquo;re completely safe and can&rsquo;t be used to run programs or deliver viruses to your device.`}
        />

        <Typography variant="h1" text="Why do we use cookies?" />
        <Typography
          variant="p"
          text={`We use first party and/or third party cookies on our website for various purposes such as:`}
        />
        <ul>
          <li>To facilitate the operation and functionality of our website;</li>
          <li>
            To improve your experience of our website and make navigating around them quicker and
            easier;
          </li>
          <li>
            To allow us to make a bespoke user experience for you and for us to understand what is
            useful or of interest to you;
          </li>
          <li>To analyze how our website is used and how best we can customize it;</li>
          <li>
            To identify future prospects and personalize marketing and sales interactions with it;
          </li>
          <li>To facilitate the tailoring of online advertising to your interests.</li>
          <li>You: a person or entity that is registered with PokeSwap.io to use the Services.</li>
        </ul>

        <Typography variant="h1" text="What type of cookies does PokeSwap.io use?" />
        <Typography
          variant="p"
          text={`Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you&rsquo;re visiting are called &ldquo;first party cookies&rdquo;.`}
        />
        <Typography
          variant="p"
          text={`Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.`}
        />
        <Typography variant="p" text={`We use the following types of cookies in our website:`} />
        <Typography variant="h1" text="Essential Cookies" />
        <Typography
          variant="p"
          text={`We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.`}
        />
        <Typography variant="h1" text="Performance and Functionality Cookies" />
        <Typography
          variant="p"
          text={`These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.`}
        />
        <Typography variant="h1" text="Marketing Cookies" />
        <Typography
          variant="p"
          text={`These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.`}
        />
        <Typography variant="h1" text="Analytics and Customization Cookies" />
        <Typography
          variant="p"
          text={`These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our website for you.`}
        />
        <Typography
          variant="p"
          text={`We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at: https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our Websites by visiting: https://tools.google.com/dlpage/gaoptout.`}
        />
        <Typography variant="h1" text="Advertising Cookies" />
        <Typography
          variant="p"
          text={`These cookies collect information over time about your online activity on the website and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it&rsquo;s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.`}
        />
        <Typography variant="h1" text="Social Media Cookies" />
        <Typography
          variant="p"
          text={`These cookies are used when you share information using a social media sharing button or "like" button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.`}
        />
        <Typography variant="h1" text="Third Party Cookies" />
        <Typography
          variant="p"
          text={`Some cookies that have been set on our website are not set on a first party basis by PokeSwap.io. The Websites can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.`}
        />
        <Typography variant="h1" text="How you can manage cookies?" />
        <Typography
          variant="p"
          text={`Most browsers allow you to control cookies through their &rsquo;settings&rsquo; preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.`}
        />
        <Typography
          variant="p"
          text={`Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.`}
        />
        <ul>
          <li>Google Chrome</li>
          <li>Internet Explorer</li>
          <li>Mozilla Firefox</li>
          <li>Safari (Desktop)</li>
          <li>Safari (Mobile)</li>
          <li>Android Browser</li>
          <li>Opera</li>
          <li>Opera Mobile</li>
        </ul>

        <Typography variant="h1" text="Blocking and disabling cookies and similar technologies" />
        <Typography
          variant="p"
          text={`Wherever you&rsquo;re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser&rsquo;s help menu for more information.`}
        />

        <Typography variant="h1" text="Changes To Our Cookie Policy" />
        <Typography
          variant="p"
          text={`We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.`}
        />

        <Typography variant="h1" text="Your Consent" />
        <Typography
          variant="p"
          text={`By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.`}
        />
        <Typography variant="h1" text="Contact Us" />
        <Typography
          variant="p"
          text={`Don&rsquo;t hesitate to contact us if you have any questions regarding our Cookie Policy.`}
        />
      </div>
    </div>
  );
}
